---
apiVersion: v1
kind: Service
metadata:
  name: s1-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: splunk-s1-standalone
  ports:
    - name: splunkweb
      port: 8000
      nodePort: 30800
    - name: splunkrest
      port: 8089
      nodePort: 30890
